### ISSUE TITLE
5.22.2.1?

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#149]
In https://github.com/perl11/cperl/issues/145#issuecomment-220767557 you said:

> With this one it looks like we'd really need a 5.22.3

Would it not be more beneficial for cperl to adopt the strawberry/activestate versioning model of having a 4th version tuple? This way when/if cperl 5.22.3 appears, it is easier for downstream packagers to go "aha - this is likely kinda-sorta similar to pumpkin 5.22.2 perl".

**Comment by rurban** [comment]
True for 5.22 but not anymore for 5.24 and following. 5.24c will contain many more changes which might eventually come with 5.26 or 5.28 given their speed, or not at all, given their unwillingness to cooperate. Even more so with 5.26c

**Comment by ribasushi** [comment]
All fair points, I wasn't aware the 5.24+ timeline was more ambitious than "damage control". I'll close this ticket as N/A.

**Comment by rurban** [comment]
I'm still thinking about it, because the plan is still close to their development schedule, and it would be much easier to fix the XS logic with a forth PERL_?_VERSION for API compat. And it would be easier for users.
I will merge their changes with every new major release. 

But the signatures, classes and native types are major changes, which will deviate much more than the tiny changes they'll do in 5.26 and 5.28.

5.24c vs 5.24 API changes are for now: OP_SIGNATURE. op->op_rettype

**Comment by ribasushi** [comment]
I see, and also fair point ;)

**Comment by rurban** [comment]
well, the 4th version is usually the build number.
the 3rd the iteration/subversion while keeping backcompat. I see no strong reason to match perl5 subversions with our subversions, most interesting is only the version, and even there we deviate a bit.

in summary, the version and subversion matches loosely but not closely. the version is always merged, the subversion not.
