### ISSUE TITLE
YAML.pm available in releases, but *not* available in master

### ISSUE THREAD

**Issue by ribasushi** [perl11/cperl#155]
Is this intentional? The side effect is that distroprefs can not be applied. I can always install YAML by hand, but my understanding was that since 5.22.2 this is no longer necessary...

Please clarify

**Comment by ribasushi** [comment]
Hm... I can clearly see YAML [in master](https://github.com/perl11/cperl/tree/master/cpan/YAML-LibYAML)

Yet I get this [clear indication YAML is not available](https://travis-ci.org/dbsrgits/dbix-class/jobs/136074035#L767)

**Comment by rurban** [comment]
Well, cperl provides the old PP YAML and now also the YAML::XS.

Looks more like another Package::Stash::XS bug. So far I've filed 2 pull requests and add 2 more patches to my distroprefs with them, but no reaction since 2015.
c++ compilation will also fail with Package::Stash::XS, 
and the dependency ExtUtils::MakeMaker::Dist::Zilla::Develop creates wrong code also.
Their travis setup is also broken, looks like this module is unmaintained.

**Comment by ribasushi** [comment]
I [minimized a test case](https://github.com/ribasushi/dbix-class/blob/5f12f0c0da16b94a85f35918e32c033bd1d312a6/.travis.yml#L123-L136): only compile cperl and nothing else, and then look for -MYAML

The result [on latest master](https://travis-ci.org/ribasushi/dbix-class/jobs/136394444#L500-L572) is ["nope"](https://travis-ci.org/ribasushi/dbix-class/jobs/136394444#L574);

**Comment by ribasushi** [comment]
Note - I am specifically looking for `YAML.pm` because this is what your CPAN.pm [is looking for](https://github.com/perl11/cperl/blob/master/cpan/CPAN/lib/CPAN/FirstTime.pm#L934)

**Comment by rurban** [comment]
cperl provides the old YAML files 
`cpan/CPAN-Meta-YAML/lib/CPAN/Meta/YAML.pm` (i.e YAML::Tiny)
plus the new `YAML::XS`. YAML.pm from PP YAML was never in perl, and not in cperl.
If you specify **YAML** as default YAML reader in your cpan config settings you need to install it.
Recommended is `YAML::Syck` and now also the cperl version of `YAML::XS`, but YAML::XS is still a bit annoying.

I didn't touch the CPAN default, which is clearly an upstream CPAN bug. YAML should never be the default YAML reader. Either the slow and permissive `CPAN::Meta::YAML` which is in core, or the fast `YAML::Syck` or `YAML::XS` 0.70.
See also http://blogs.perl.org/users/rurban/2016/03/more-on-yaml-syck-looks-much-better.html, http://blogs.perl.org/users/rurban/2016/03/on-yaml-and-yamlxs-inconsistencies.html and http://blogs.perl.org/users/rurban/2016/03/yaml-patches-done.html

**Comment by ribasushi** [comment]
Right - this is why I filed the issue: perhaps you changing the cperl's CPAN default makes sense, especially given you already provide a yaml lib. After all CPAN.pm _is_ your bootstraping mechanism.

**Comment by rurban** [comment]
Yes, I'll be doing that. Good idea.
Normally you already have perl5 with cpan installed, with the very bad YAML as default reader, which is the worst of all choices. Advanced users changed that to YAML::Syck, 10x faster.
cperl offers now also a fixed YAML::XS, but I cannot set that as default, because the old YAML::XS will write files that YAML will not be able to read. For compat with perl5. `~/.cpan/` is used by perl5 and cperl.

The core CPAN::Meta::YAML has no YAML 1.2 feature support:

```
Alert: While trying to 'dump' YAML file
 '/Users/rurban/.cpan/build/Test-Simple-1.302022-b_dt7C.yml'
with 'CPAN::Meta::YAML' the following error was encountered:
  CPAN::Meta::YAML does not support CPAN::Distribution references at /usr/local/lib/cperl/5.24.0/darwin@de66004/CPAN.pm line 613.
```

how lame! working in the `feature/CPAN-Meta-YAML-1.2` branch on that

**Comment by rurban** [comment]
8393bc336cfa89affa86de82ed4cf2e96d2f094d merged to master
