### ISSUE TITLE
More complete cperl examples?

### ISSUE THREAD

**Issue by kberov** [perl11/cperl#343]
I looked at http://perl11.org/cperl/
There are some short examples in the document, but is there any full featured examples showing how code would look like? For example a [typical class](http://perl11.org/cperl/perlclass.html), or script [using types](http://perl11.org/cperl/perltypes.html) and new keywords?
Another marketer for this project would be a tutorial how to compile a program using classes to a binary executable file, linked statically or dynamically. Is there such example on the site?
Another question is how to create a module for CPAN, which can be tested by cpantesters? Obvously there need to be cperl installed somewhere. How do we recognize in which perl we are? etc. Mostly user questions.
Thanks!

**Comment by rurban** [comment]
* classes not yet. they are not fully finished. I will then convert most of the already modernized modules to use classes also, such as Test::Simple, Pod::Simple, bigint to use classes.
* types: see above. The core modules who benefit most are already modernized to use signatures with types, and thus are 2x faster and safer. Each typed module has a "c" suffix, because perl5 cannot read typed signatures yet, only the old lexical declarations from 5.6 can use types.
* perlcc is used to compile scripts, as before. If statically or dynamically depends on how libperl is defined, static or shared.
* cpan/cpantesters: since upstream, both p5p and the toolchain gang, still boycott any cooperation it's hard. So far their argument was that I'm technically wrong, and they are right. This changed recently. The next argument was a religious one, that I don't express enough "faith" in the devs and thereby violated their code of conduct. Literally.
Their latest argumentation is that nobody wants to work with me, because I'm "uncivil". Which also a bogus argument, because they are the ones who are uncivil and I was the one who acted professionally.  It will eventually settle itself, once they'll notice that perl5 cannot be used anymore, and they'll have to switch to cperl and proper management. The destruction done is accelerating, security issues are piling up and the feature differences enhance greatly. Once cperl is 2x faster and better there's no p5p anymore.
I don't even have a travis or appveyor smoking for recipe for myself yet.

* how detect? this should be in `cperldoc perlcperl`.
  How to detect cperl?
    ""$^V" =~ /c$/"
    config.h defines <USE_CPERL>
    Config.pm defines "usecperl"
    cperl changed modules end with "c", typically "_01c".
    Libraries are installed into /usr/local/lib/cperl, not
    /usr/local/lib/perl5.

**Comment by kberov** [comment]
Thank you for the detailed reply, @rurban !
Yes, I've read your blog.
From all my heart I hope thinks will settle and there will be understanding and collaboration.
It is even hard to find job as a Perl programmer here in Central and Eastern Europe. If one finds it is usually to maintain a very old application, until it is replaced with something written in another language.
