### ISSUE TITLE
for(range) + infinite loop hangs

### ISSUE THREAD

**Issue by constantined** [perl11/cperl#349]
How to reproduce:
```sh
cperl -e 'exit; for(1..2){while(){}}'
```
I tried 5.27.2 and 5.26.1 on Linux and also cperl-5.27.2-mingw-x64 binary package on Windows with the same result.

**Comment by constantined** [comment]
Thanks, seems like 1be2420bafbac8026b04ea70291864851e3ee964 fixed this issue.
Note that it affects at least t/live*.t tests of Net::HTTP.

**Comment by rurban** [comment]
Ah, I had the same problem on Net::HTTP
Needs to be backported to maint-5.26c

**Comment by rurban** [comment]
Fixed, er, worked around with 59338f943ad55f6122a65753ba6840f758ded25c
for v5.26.2c. See below, this fix was unstable.

**Comment by rurban** [comment]
Fixed for master with 2c86e07c84c7889c58e74a6f2ad3c60c49d201e3
for 5.26.2c with 899f6dae48869440a3338af9e085ace514d46de3

We really need to avoid descending into inner loops, as they are all cycling endlessly.
On master (5.27.3c) we even skipped to loop oob check in the body at all, when we changed the iter to a LOGOP. That's why the error disappeared.
