### ISSUE TITLE
./configure : no such file or directorie

### ISSUE THREAD

**Issue by Azaretdodo** [perl11/cperl#410]
Hello,

your first command line asked don't works :

./configure : no such file or directorie

thank you in advance to help myself install your fork,

Regards.

Azaretdodo.

**Comment by eloj** [comment]
Seems fairly obvious, there's no such file to run as './configure'. There is a script called "./Configure" though. Note the Capital C.

A digression:

You've been leaving a large number of more-or-less incomprehensible (as in "what are you even trying to do?) issues in many different projects now. Most of the time the issue seems to be that you're not following the instructions as written, other times it's not even clear what you're trying to do, like running generator scripts no end-user would have a reason to run.

Please don't open new issues when you haven't even spent ten seconds trying to understand what's going wrong, and when you do, explain _what_ you're trying to accomplish, **especially if you've edited build scripts**, and _why_.

**Comment by Azaretdodo** [comment]
This isn't often when anyone choose to uppercase configure

I don't know why you have did that

But I have know this laster time than Linux doesn't understand between itselfs uppercase and lowercase when I were interested in cmake scripting :)

Don't worried be happy

Thank you for your e-mail,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by eloj** [comment]
If this issue is now solved to your liking, you should close it.
